### ISSUE TITLE
Add a gitignore file.

### ISSUE THREAD

**Issue by glogiotatidis** [iokouts/event-calendar#1]
Το repository έχει πολλά `*.pyc` και `.*~` αρχεία. Τα πρώτα είναι compiled python και τα δεύτερα είναι backup αρχεία του editor. Και τα δύο δεν πρέπει να είναι εδώ.
1. Τα σβήνουμε από το git. 

```
git rm -r *pyc
git rm -r *~
```
1. Φτιάχνουμε ένα αρχείο `.gitignore` στο root folder του repository και βάζουμε

```
*.pyc
*~
```

και κανουμε το `.gitignore` comit

**Comment by iokouts** [comment]
got it!
