### ISSUE TITLE
Better names

### ISSUE THREAD

**Issue by glogiotatidis** [iokouts/event-calendar#2]
Naming things is important.

https://github.com/iokouts/event-calendar/blob/master/redcalendar/events/models.py#L12-L15

Τα `event_name`, `event_date` κτλ όλα είναι attributes του `Event`, οπότε μπορούν απλά να απλοποιηθούν σε `name`, `date` κτλ. Έτσι όταν έχεις ένα event object, θα βρεις το όνομα του στο `name`.

```
event = Event()
event.name 
```

αντί για `event.event_name`

**Comment by iokouts** [comment]
done
